#!/usr/bin/env node
/** Deep production-backed campaign, SCORE, Echo, scarcity, and habitat audit. */
import { mkdirSync, writeFileSync } from 'node:fs'; import { performance } from 'node:perf_hooks';
import { RunController } from '../../src/simulation/simulator.js'; import { scoreResult } from '../../src/game/scoring.js';
import { defaultMeta } from '../../src/platform/storage.js'; import { MEMORY_NODES, availableMemoryNodes, compileMemory, purchaseMemory } from '../../src/game/skills/index.js';
const smoke=process.argv.includes('--smoke');const freshCount=smoke?16:200;const campaignCount=smoke?2:10;const progressionCount=smoke?6:40;
const started=performance.now();const policies=['cheapest','balanced','potential','resource','habitat','cold','marine'];
const fresh=[];for(let i=0;i<freshCount;i++)fresh.push(runWorld(0x100000+i,1,defaultMeta()));
const campaigns={};for(const policy of policies){const rows=[];for(let cohort=0;cohort<campaignCount;cohort++)rows.push(runCampaign(0x200000+cohort*97,policy));campaigns[policy]=campaignSummary(rows)}
const progression={};for(const [label,count] of [['fresh',0],['quarter',63],['half',126],['full',252]]){const meta=legalOwnership(count);const rows=[];for(let i=0;i<progressionCount;i++)rows.push(runWorld(0x300000+i,12,meta));progression[label]=worldSummary(rows);progression[label].skills=count;progression[label].potential=compileMemory(meta).worldPotential;}
const freshSummary=worldSummary(fresh);const typical=campaigns.potential;const strong=progression.full;
const valid=freshSummary.score.median>=8000&&freshSummary.score.median<=15000&&freshSummary.durationSeconds.median>=270&&freshSummary.durationSeconds.median<=330
  &&((freshSummary.causes['resource-exhaustion']??0)+(freshSummary.causes['maintenance-starvation']??0))/freshCount>=.75&&freshSummary.events.max===0
  &&typical.world3Score.median>=80000&&typical.world3Score.median<=130000&&typical.skillsAfter3.median>=5&&typical.skillsAfter3.median<=10
  &&typical.firstPressureMinutes.median>=13&&typical.firstPressureMinutes.median<=16&&typical.firstCycle1xMinutes5.median>=18&&typical.firstCycle1xMinutes5.median<=24&&strong.score.median>=850000&&strong.score.median<=1100000&&strong.score.p90<=1250000&&strong.hardMaximumRate<=.3
  &&strong.peakReach.median<.85&&strong.marineVisitedShare.median<.6;
const report={date:new Date().toISOString(),mode:smoke?'smoke':'full',productionAuthority:true,elapsedMs:Number((performance.now()-started).toFixed(1)),
 fresh:freshSummary,campaigns,progression,targets:{freshScore:'8k–15k median',freshDuration:'270–330 s',threeWorldScore:'80k–130k',fullScore:'850k–1.1m'},valid};
mkdirSync('reports',{recursive:true});writeFileSync(`reports/campaign-audit-${smoke?'smoke':'full'}.json`,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));if(!valid)process.exitCode=1;
function runCampaign(seedBase,policy){let meta=defaultMeta(),elapsed=0,firstPressure=null;const worlds=[];for(let ordinal=1;ordinal<=5;ordinal++){const world=runWorld(seedBase+ordinal,ordinal,meta);worlds.push(world);if(ordinal<=3)elapsed+=world.result.survivalSeconds;if(ordinal===3&&world.scheduledFirstEvent!=null)firstPressure=(worlds[0].result.survivalSeconds+worlds[1].result.survivalSeconds+world.scheduledFirstEvent/10)/60;
 meta={...meta,runs:ordinal,totalEchoes:meta.totalEchoes+world.score.echoes,echoBalance:meta.echoBalance+world.score.echoes,bestScore:Math.max(meta.bestScore,world.score.total),scoreModelVersion:2};buyAvailable(meta,policy,(next)=>{meta=next});
 world.ownedAfter=meta.memoryNodes.length;world.potentialAfter=compileMemory(meta).worldPotential;}
 return{worlds,meta,elapsedSeconds3:worlds.slice(0,3).reduce((n,w)=>n+w.result.survivalSeconds,0),firstPressureMinutes:firstPressure};}
function runWorld(seed,ordinal,meta){const memory=compileMemory(meta);const controller=new RunController({seed,worldOrdinal:ordinal,worldPotential:memory.worldPotential,potentialVersion:memory.potentialVersion,
 memoryEffects:memory.effects,memoryConditionals:memory.conditionals,memoryUnlocks:memory.unlocks,habitatCapabilities:memory.habitatCapabilities});controller.start();controller.advance(4000);
 const result=controller.buildResult();return{result,score:scoreResult(result),scheduledFirstEvent:controller.state.events[0]?.startTick??null,eventCount:controller.state.events.length};}
function buyAvailable(meta,policy,commit){let guard=0;while(guard++<252){const available=[...availableMemoryNodes(meta)];if(!available.length)break;const node=choose(available,meta,policy);const tx=purchaseMemory(meta,node.id);if(!tx.ok)break;meta=tx.meta;commit(meta);}}
function choose(nodes,meta,policy){if(policy==='cheapest')return nodes.sort((a,b)=>a.cost-b.cost||b.evolutionPower-a.evolutionPower)[0];if(policy==='balanced'){const counts=Object.fromEntries(['Reach','Flow','Reserve','Ecology','Perception','Continuity'].map((branch)=>[branch,0]));for(const id of meta.memoryNodes)counts[MEMORY_NODES.find((node)=>node.id===id)?.branch]++;return nodes.sort((a,b)=>counts[a.branch]-counts[b.branch]||b.evolutionPower/a.cost-a.evolutionPower/b.cost)[0];}
 const wanted=policy==='resource'?/uptake|maintenance|energyCap|reserve/i:policy==='habitat'?/ACCESS/:policy==='cold'?/TUNDRA|SNOW_ICE|cold/i:policy==='marine'?/OCEAN|hydrostatic/i:null;
 return nodes.sort((a,b)=>(wanted?.test(JSON.stringify(a.effect))?0:1)-(wanted?.test(JSON.stringify(b.effect))?0:1)||b.evolutionPower/b.cost-a.evolutionPower/a.cost)[0];}
function legalOwnership(count){let meta={...defaultMeta(),echoBalance:1_000_000};while(meta.memoryNodes.length<count){const tx=purchaseMemory(meta,availableMemoryNodes(meta)[0].id);if(!tx.ok)throw new Error('legal ownership traversal stopped');meta=tx.meta;}return meta;}
function worldSummary(rows){const scores=rows.map((row)=>row.score.total),durations=rows.map((row)=>row.result.survivalSeconds),echoes=rows.map((row)=>row.score.echoes),peak=rows.map((row)=>row.result.peakCoverage),sustained=rows.map((row)=>row.result.sustainedCoverage),reserve=rows.map((row)=>row.result.resourceInitial?row.result.resourceFinal/row.result.resourceInitial:0),events=rows.map((row)=>row.eventCount);
 const marine=rows.map((row)=>{const occupied=row.result.habitatOccupancy??[],total=occupied.reduce((a,b)=>a+b,0);return total?(occupied[0]+occupied[1])/total:0;});
 return{worlds:rows.length,score:dist(scores),echoes:dist(echoes),durationSeconds:dist(durations),peakReach:dist(peak),sustainedReach:dist(sustained),resourceRemaining:dist(reserve),marineVisitedShare:dist(marine),events:dist(events),causes:counts(rows.map((row)=>row.result.cause)),hardMaximumRate:rows.filter((row)=>row.result.terminalCause==='hard-maximum').length/rows.length};}
function campaignSummary(rows){return{cohorts:rows.length,elapsed1xMinutes3:dist(rows.map((row)=>row.elapsedSeconds3/60)),firstCycle1xMinutes5:dist(rows.map((row)=>row.worlds.reduce((sum,world)=>sum+world.result.survivalSeconds,0)/60)),skillsAfter3:dist(rows.map((row)=>row.worlds[2].ownedAfter)),potentialAfter3:dist(rows.map((row)=>row.worlds[2].potentialAfter)),world3Score:dist(rows.map((row)=>row.worlds[2].score.total)),world4Score:dist(rows.map((row)=>row.worlds[3].score.total)),bestScore:dist(rows.map((row)=>row.meta.bestScore)),finalSkills:dist(rows.map((row)=>row.meta.memoryNodes.length)),echoBalance:dist(rows.map((row)=>row.meta.echoBalance)),firstPressureMinutes:dist(rows.map((row)=>row.firstPressureMinutes).filter(Number.isFinite))};}
function counts(values){return Object.fromEntries([...Map.groupBy(values,(value)=>value)].map(([key,rows])=>[key,rows.length]))}
function dist(values){if(!values.length)return{min:null,p10:null,p25:null,median:null,p75:null,p90:null,max:null};const a=values.slice().sort((x,y)=>x-y),at=(p)=>round(a[Math.floor((a.length-1)*p)]);return{min:round(a[0]),p10:at(.1),p25:at(.25),median:at(.5),p75:at(.75),p90:at(.9),max:round(a.at(-1))}}
function round(value){return Number(Number(value).toFixed(5))}
