/** Authored Evolution archetypes, independent of their repeated cell layout. */
export const EVOLUTION_DOMAINS = Object.freeze([
  'Foundation', 'Fertility', 'Freshwater', 'Scarcity', 'Cryogenic', 'Marine', 'Luminous',
]);

const trait = (key, value) => Object.freeze({ kind: 'trait', key, value });
const ecology = (key, value = 1) => Object.freeze({ kind: 'ecology', key, value });
const habitat = (capability) => Object.freeze({ kind: 'habitat', capability });
const worldmaking = (key) => Object.freeze({ kind: 'worldmaking', key });
const luminous = (key, value) => Object.freeze({ kind: 'luminous', key, value });
const defense = (affinity, value) => Object.freeze({ kind: 'defense', affinity, value });
const skill = (id, name, domain, tier, cost, summary, description, effects, kind = 'specialization') => Object.freeze({
  id, nameEn: name, domain, tier, cost, kind, summary, description, effects: Object.freeze(effects),
  refinementCost: Math.max(1, Math.round(cost / 3)),
});

/** Every repeated cell inherits one authored biological role and bounded continuation. */
export const EVOLUTION_ARCHETYPES = Object.freeze([
  skill('first-division', 'First Division', 'Foundation', 0, 8,
    'Establishment and budding become more reliable.',
    'The organism learns the first dependable split: a small gain in frontier confidence that every later World inherits.',
    [trait('reach', 1.04), trait('maintenance', .78)], 'root'),

  skill('reliable-budding', 'Reliable Budding', 'Foundation', 1, 16,
    'New cells establish more often from a viable parent.',
    'Buds waste less of the parent’s stored energy when a favorable neighboring cell is open.',
    [trait('reach', 1.13)]),
  skill('nutrient-uptake', 'Nutrient Uptake', 'Foundation', 1, 16,
    'Living cells convert local nutrients more effectively.',
    'Absorption rises without creating nutrients; richer cells still visibly matter.',
    [trait('uptake', 1.12)]),
  skill('frugal-membrane', 'Frugal Membrane', 'Foundation', 1, 16,
    'Every living cell costs less to maintain.',
    'A tighter membrane lowers chronic energy demand but does not prevent eventual exhaustion.',
    [trait('maintenance', .85)]),
  skill('energy-reserve', 'Energy Reserve', 'Foundation', 1, 18,
    'Cells can hold a larger reserve before a lean spell.',
    'Storage extends local recovery windows; it cannot replace food.',
    [trait('energyCap', 1.20)]),
  skill('local-repair', 'Local Repair', 'Foundation', 1, 18,
    'Stressed tissue recovers more steadily.',
    'Minor damage is repaired locally, improving stress resistance without restoring dead networks for free.',
    [trait('stressResist', 1.12), trait('regrow', 1.08)]),

  skill('fertile-filaments', 'Fertile Filaments', 'Fertility', 2, 24,
    'Surplus energy supports one more local budding opportunity.',
    'Dense healthy tissue can make a modest extra attempt to establish nearby life.',
    [trait('growthCap', .25)]),
  skill('freshwater-sense', 'Freshwater Sense', 'Freshwater', 2, 24,
    'Life uses nearby freshwater support more efficiently.',
    'Wet catchments reduce local strain, especially around lakes and shores.',
    [ecology('freshwaterSupport', .12), defense('Freshwater', 80)]),
  // The deterministic green root is a hex cell. Stable Transport is the sixth
  // foundational first-ring identity; this presentation tier has no cost or
  // production-effect authority.
  skill('stable-transport', 'Stable Transport', 'Foundation', 1, 24,
    'Neighboring cells move usable energy more reliably.',
    'Transport strengthens the network after it has formed; isolated cells gain little.',
    [trait('conductance', 1.16), trait('reinforce', 1.08)]),
  skill('scarcity-patience', 'Scarcity Patience', 'Scarcity', 2, 24,
    'Life can enter somewhat poorer cells before stopping.',
    'The niche floor falls modestly, trading faster reach for more careful resource use.',
    [ecology('resourceFloorReduction', .08), defense('Scarcity', 80)]),
  skill('thermal-buffer', 'Thermal Buffer', 'Cryogenic', 2, 26,
    'Short climate swings cause less immediate stress.',
    'A buffered interior broadens heat and moisture tolerance without making harsh biomes free.',
    [trait('heatTol', 1.14), trait('droughtTol', 1.10), defense('Cryogenic', 70)]),
  skill('lake-crossing', 'Lake Crossing', 'Freshwater', 2, 28,
    'Lake cells become a viable connected habitat.',
    'Freshwater can now carry the organism across a lake, with the same upkeep costs as other living tissue.',
    [habitat('LAKE_ACCESS'), defense('Freshwater', 70)]),
  skill('bioelectric-spark', 'Bioelectric Spark', 'Luminous', 2, 28,
    'Viable high-flux cells can begin a modest visible charge.',
    'The first Luminous lesson turns real transport into a warm cellular glow, paid for with setup and upkeep energy.',
    [luminous('enabled', 1), luminous('generation', .64), luminous('domain', .62), luminous('upkeep', .10), luminous('visual', .18), defense('Luminous', 60)]),
  skill('light-retention', 'Light Retention', 'Luminous', 2, 30,
    'Charge survives brief interruptions for longer.',
    'Powered cells lose less charge after transport falters, but unpowered charge still decays away.',
    [luminous('retention', .004), luminous('visual', .05), defense('Luminous', 70)]),
  skill('recycling-matrix', 'Recycling Matrix', 'Scarcity', 2, 30,
    'Spent local matter can slowly return to a usable state.',
    'Recycling delays collapse in depleted cells and always draws from bounded recyclable stock.',
    [worldmaking('reclamation'), ecology('recycling', .18), defense('Scarcity', 90)]),
  skill('tidal-tolerance', 'Tidal Tolerance', 'Marine', 2, 30,
    'The organism can hold the shallow ocean edge.',
    'Coastal water opens as habitat with a noticeable maintenance burden.',
    [habitat('SHALLOW_OCEAN_EDGE_ACCESS'), ecology('marineSupport', .10), defense('Marine', 80)]),

  skill('wetland-exchange', 'Wetland Exchange', 'Freshwater', 3, 38,
    'Freshwater niches renew local energy more steadily.',
    'Wet living cells share catchment support while still consuming their finite local resource.',
    [ecology('freshwaterSupport', .18), trait('maintenance', .95), defense('Freshwater', 100)]),
  skill('brackish-budding', 'Brackish Budding', 'Marine', 3, 38,
    'Shallow ocean cells can establish life beyond the coast.',
    'Marine reach broadens slowly and costs more to maintain than a favorable land niche.',
    [habitat('SHALLOW_OCEAN_ACCESS'), ecology('marineSupport', .16), defense('Marine', 100)]),
  skill('cold-reserve', 'Cold Reserve', 'Cryogenic', 3, 40,
    'Cold cells keep a deeper emergency reserve.',
    'Seasonal cold becomes survivable for longer, but the stored energy must first be earned.',
    [habitat('TUNDRA_ACCESS'), trait('coldReserve', .35), defense('Cryogenic', 100)]),
  skill('shore-rooting', 'Shore Rooting', 'Freshwater', 3, 40,
    'Shore and wetland cells sustain a lower resource threshold.',
    'Life can stay connected around water margins instead of treating each wet cell as a dead end.',
    [ecology('freshwaterSupport', .14), ecology('resourceFloorReduction', .05), defense('Freshwater', 100)]),
  skill('deep-reserve', 'Deep Reserve', 'Scarcity', 3, 42,
    'Energy storage and maintenance efficiency improve together.',
    'A slower scarcity path gives established cells more time to redistribute real reserves.',
    [trait('energyCap', 1.14), trait('maintenance', .94), defense('Scarcity', 100)]),
  skill('glacial-basins', 'Glacial Basins', 'Cryogenic', 3, 44,
    'Cold terrain can form bounded freshwater basins.',
    'Prepared cold cells may become small lakes when they can pay the nutrient and energy cost.',
    [habitat('SNOW_ICE_ACCESS'), trait('coldReserve', .45), trait('maintenance', .94), worldmaking('cryolake'), defense('Cryogenic', 120)]),
  skill('cohesive-repair', 'Cohesive Repair', 'Foundation', 3, 44,
    'Broken routes reinforce and reconnect more readily.',
    'Repair favors existing living neighborhoods rather than reviving distant dead cells.',
    [trait('reinforce', 1.16), trait('regrow', 1.16)]),
  skill('marine-bridge', 'Marine Bridge', 'Marine', 3, 46,
    'Deep ocean cells become a costly viable habitat.',
    'The world opens dramatically, but marine cells place real demand on transport and maintenance.',
    [habitat('DEEP_OCEAN_ACCESS'), ecology('marineSupport', .24), defense('Marine', 120)]),
  skill('powered-transport', 'Powered Transport', 'Luminous', 3, 46,
    'Charge improves transport where active flux already exists.',
    'A powered network carries energy more efficiently after paying the cost to establish charge.',
    [luminous('generation', .20), luminous('transport', .16), luminous('upkeep', -.08), luminous('visual', .07), defense('Luminous', 110)]),
  skill('luminous-recovery', 'Luminous Recovery', 'Luminous', 3, 48,
    'Powered cells recover a little more effectively after stress.',
    'Bioelectric recovery is bounded by charge and cannot operate when generation stops.',
    [luminous('recovery', .14), luminous('retention', .002), luminous('visual', .07), defense('Luminous', 120)]),

  skill('fertility-loop', 'Fertility Loop', 'Fertility', 4, 58,
    'Established fertile clusters bud and feed one another better.',
    'The gain favors a coherent rich niche; reckless spread still burns through local resources.',
    [trait('reach', 1.12), trait('uptake', 1.10), defense('Fertility', 120)]),
  skill('freshwater-garden', 'Freshwater Garden', 'Freshwater', 4, 58,
    'Freshwater networks recycle more usefully near living cells.',
    'A gardened catchment delays depletion but never creates an unbounded source.',
    [ecology('freshwaterSupport', .18), ecology('recycling', .12), defense('Freshwater', 140)]),
  skill('scarcity-compost', 'Scarcity Compost', 'Scarcity', 4, 60,
    'Depleted terrain can remain marginally useful after recycling.',
    'Compost lowers the recovery threshold at a slow, bounded rate.',
    [ecology('resourceFloorReduction', .08), ecology('recycling', .20), defense('Scarcity', 140)]),
  skill('marine-symbiosis', 'Marine Symbiosis', 'Marine', 4, 60,
    'Marine cells maintain a more stable local exchange.',
    'Ocean expansion becomes less punishing, while its greater ecological footprint remains visible.',
    [ecology('marineSupport', .20), trait('maintenance', .96), defense('Marine', 140)]),
  skill('cryogenic-rest', 'Cryogenic Rest', 'Cryogenic', 4, 62,
    'Cold life enters a lower-cost resting mode.',
    'Cold habitats become a slow survival path rather than a free shortcut around scarcity.',
    [trait('maintenance', .94), trait('stressResist', 1.12), defense('Cryogenic', 140)]),
  skill('resilient-weave', 'Resilient Weave', 'Foundation', 4, 62,
    'Large networks hold useful loops under pressure.',
    'Cohesion resists fragmentation only where a living network has actually formed.',
    [trait('redundantLoops', .35), trait('stressResist', 1.10)]),
  skill('luminous-canopy', 'Luminous Canopy', 'Luminous', 4, 64,
    'More viable high-flux cells can sustain a brighter charge.',
    'Generation grows with real network flux and remains most legible on the dark hemisphere.',
    [luminous('generation', .26), luminous('domain', .16), luminous('visual', .13), defense('Luminous', 150)]),
  skill('coastal-succession', 'Coastal Succession', 'Marine', 4, 64,
    'Suitable shallow ocean cells can become bounded coastal wetland.',
    'Worldmaking broadens habitat only after living cells pay the transformation setup cost.',
    [worldmaking('littoral'), ecology('marineSupport', .12), defense('Marine', 150)]),
  skill('deep-current', 'Deep Current', 'Luminous', 4, 66,
    'Marine flux can support charge across a wider living domain.',
    'Deep-water light is powerful only after transport and marine access have been established.',
    [luminous('domain', .18), luminous('transport', .14), luminous('upkeep', -.06), defense('Luminous', 160)]),
  skill('stewardship-cycle', 'Stewardship Cycle', 'Scarcity', 4, 66,
    'Recovery work wastes less of a stressed network.',
    'A living cycle turns bounded recycled material into a slower, more durable ecology.',
    [ecology('recycling', .22), luminous('recovery', .06), defense('Scarcity', 160)]),

  skill('fertility-crown', 'Fertility Crown', 'Fertility', 5, 82,
    'Rich established tissue can divide with exceptional reliability.',
    'This capstone creates a visibly denser fertile network but also asks it to consume more local opportunity.',
    [trait('reach', 1.15), trait('growCost', 1.08), defense('Fertility', 180)], 'capstone'),
  skill('living-waters', 'Living Waters', 'Freshwater', 5, 84,
    'Freshwater habitat becomes a durable connected refuge.',
    'Lakes, shores, and wetlands can sustain a longer ecological rhythm at continuing maintenance cost.',
    [ecology('freshwaterSupport', .25), trait('maintenance', .94), defense('Freshwater', 180)], 'capstone'),
  skill('scarcity-sanctuary', 'Scarcity Sanctuary', 'Scarcity', 5, 86,
    'A depleted network preserves more of its remaining function.',
    'The sanctuary slows collapse through efficiency and recycling, never through an infinite source.',
    [trait('maintenance', .90), ecology('resourceFloorReduction', .10), ecology('recycling', .24), defense('Scarcity', 190)], 'capstone'),
  skill('luminous-crown', 'Luminous Crown', 'Luminous', 5, 88,
    'A mature charge system becomes brighter, steadier, and cheaper to hold.',
    'The capstone remains an ecology: charge depends on living flux and falls away when the network dies.',
    [luminous('generation', .30), luminous('retention', .003), luminous('upkeep', -.14), luminous('visual', .18), defense('Luminous', 200)], 'capstone'),
  // The compact Foundation launch basin would otherwise pull the global tier-5
  // median inside tier 4. World Shaper joins the existing tier-6 finale; this
  // route label does not change its cost, effects, or compiled production law.
  skill('world-shaper', 'World Shaper', 'Foundation', 6, 90,
    'Reclamation, cold basins, and coasts work together more reliably.',
    'Worldmaking stays bounded and costly, but a mature organism can leave a visible ecological history.',
    [worldmaking('reclamation'), worldmaking('cryolake'), worldmaking('littoral'), ecology('recycling', .18)] , 'capstone'),

  skill('living-biosphere', 'Living Biosphere', 'Foundation', 6, 120,
    'A mature ecology coordinates repair, reserves, habitat, and charge.',
    'The final cell improves several established systems at once, yet finite resources and rising Environment pressure still end every World.',
    [trait('maintenance', .92), trait('stressResist', 1.10), luminous('generation', .16), luminous('recovery', .10), ecology('resourceFloorReduction', .05)], 'capstone'),
]);

export const EVOLUTION_ARCHETYPE_IDS = Object.freeze(EVOLUTION_ARCHETYPES.map((archetype) => archetype.id));
